REVOKE ALL ON DATABASE leave_approval FROM PUBLIC;
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'leave_api') THEN
        CREATE ROLE leave_api LOGIN PASSWORD 'leave_api' NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
    END IF;
END;
$$;

GRANT CONNECT ON DATABASE leave_approval TO leave_api;
